[general]
    max_timeouts=3
    runs        =2
    timeout     =30
    warmups     =1

[[developers]]
    username="xeraph-dev"
[[developers]]
    username="el-garro"

[[languages]]
    build       ="go build -o build/:challenge-:developer cmd/:challenge/:developer/main.go"
    cmd         ="build/:challenge-:developer"
    name        ="go"
    simple_build=false
[[languages]]
    build       ="swift build -c release"
    cmd         =".build/release/:challenge-:developer"
    name        ="swift"
    simple_build=true

[[challenges]]
    key ="aoc-year2015-day4"
    name="Advent of Code - Year 2015 - Day 4"
    [[challenges.levels]]
        input =["5", "yzbqklnj"]
        name  ="5 zeros"
        output="282749"
    [[challenges.levels]]
        input =["6", "yzbqklnj"]
        name  ="6 zeros"
        output="9962624"
    [[challenges.levels]]
        input =["7", "yzbqklnj"]
        name  ="7 zeros"
        output="57551859"
    [[challenges.developers]]
        languages=["swift"]
        username ="xeraph-dev"
    [[challenges.developers]]
        languages=["go"]
        username ="el-garro"
[[challenges]]
    key ="aoc-year2020-day15"
    name="Advent of Code - Year 2020 - Day 15"
    [[challenges.levels]]
        input =["0", "1", "19", "2", "30000000", "5", "9"]
        name  ="30000000th number spoken"
        output="62714"
    [[challenges.developers]]
        languages=[]
        username ="xeraph-dev"
    [[challenges.developers]]
        languages=[]
        username ="el-garro"
