version: "3"

tasks:
  default:
    deps: [go, rust, swift, zig]

  bench:
    deps: [default, bench:aoc-year2015-day4]

  bench:aoc-year2015-day4:
    deps: [default]
    cmds:
      - ./bench aoc-year2015-day4

  go:
    dir: go
    cmds: [task]

  rust:
    dir: rust
    cmds: [cargo build --release]

  swift:
    dir: swift
    cmds: [swift build -c release]

  zig:
    dir: zig
    cmds: [zig build]
